run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
  - format: colored-line-number
  print-issued-line: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/catherinevee/driftmgr
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  govet:
    enable:
    - atomicalign
    - deepequalerrors
    - findcall
    - nilness
    - reflectvaluecompare
    - unusedwrite
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    for-loops: true
    range-loops: true
    slice-append: true
  revive:
    min-confidence: 0
  unused:
    check-exported: false

linters:
  enable:
  - bodyclose
  - copyloopvar
  - dogsled
  - dupl
  - errcheck
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - mnd
  - nakedret
  - noctx
  - nolintlint
  - prealloc
  - revive
  - rowserrcheck
  - predeclared
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace

issues:
  uniq-by-line: true
  exclude-rules:
  - path: _test\.go
    linters:
    - mnd
    - gocyclo
    - goconst
  - path: cmd/
    linters:
    - mnd
  - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv) is not checked"
    linters:
    - errcheck
  - text: "exported (function|method|type|var|const) .* should have comment"
    linters:
    - revive
  - text: "should have a package comment"
    linters:
    - revive
