version: "3.8"

services:
  # Development service with hot reloading
  driftmgr-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/tmp
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  # Production service
  driftmgr:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_REGION=us-east-1
      - AZURE_LOCATION=eastus
      - GCP_REGION=us-central1
    volumes:
      - ./config:/config:ro
      - ./output:/output
    restart: unless-stopped

  # Test service for running tests in container
  driftmgr-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: make test-coverage
    environment:
      - CGO_ENABLED=1 # Enable for race detection
      - GOOS=linux

networks:
  default:
    name: driftmgr-network
