apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: driftmgr
  labels:
    app: analysis-service
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
        version: v1.0.0
    spec:
      containers:
      - name: analysis-service
        image: driftmgr/analysis-service:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: redis-url
        - name: DISCOVERY_SERVICE_URL
          value: "http://discovery-service:8081"
        - name: ML_SERVICE_URL
          value: "http://ml-service:8090"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: driftmgr
  labels:
    app: analysis-service
spec:
  selector:
    app: analysis-service
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analysis-service-ingress
  namespace: driftmgr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: analysis.driftmgr.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: analysis-service
            port:
              number: 8082
  tls:
  - hosts:
    - analysis.driftmgr.local
    secretName: driftmgr-tls
