apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: driftmgr
  labels:
    app: discovery-service
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
        version: v1.0.0
    spec:
      containers:
      - name: discovery-service
        image: driftmgr/discovery-service:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: redis-url
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: aws-secret-access-key
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: azure-client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: azure-client-secret
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: azure-tenant-id
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: gcp-project-id
        - name: GCP_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: driftmgr-secrets
              key: gcp-credentials
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: driftmgr-config
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: driftmgr
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery-service-ingress
  namespace: driftmgr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: discovery.driftmgr.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: discovery-service
            port:
              number: 8081
  tls:
  - hosts:
    - discovery.driftmgr.local
    secretName: driftmgr-tls
