defaults:
  provider: aws
  region: us-east-1
  parallel_imports: 5
  retry_attempts: 3

aws:
  profile: default
  assume_role_arn: null
  session_duration: 3600

azure:
  subscription_id: ""
  tenant_id: ""
  client_id: ""

gcp:
  project_id: ""
  credentials_file: ""
  region: us-central1

import:
  dry_run: false
  generate_config: true
  validate_after_import: true
  backup_state: true

ui:
  theme: dark
  show_progress: true
  log_level: info
