# Simplified DriftMgr Configuration
# This configuration disables authentication to avoid database issues

server:
  port: 8080
  host: "localhost"

discovery:
  aws_profile: "default"
  azure_profile: "default"
  gcp_project: ""
  digitalocean_token: ""

security:
  enable_auth: true  # Enable authentication for production safety

logging:
  level: "info"
  format: "text"
  output: "stdout"

database:
  type: "sqlite"
  database: "driftmgr.db"
