# Development Configuration for DriftMgr
# This configuration is optimized for local development

server:
  port: 8080
  host: "localhost"
  debug: true
  tls:
    enabled: false  # No TLS in development

discovery:
  timeout: 5m
  concurrency_limit: 5
  batch_size: 50
  retry_attempts: 2
  retry_delay: 2s
  enable_caching: true
  cache_ttl: 1m
  cache_max_size: 100
  api_timeout: 30s

providers:
  aws:
    profile: "default"
    regions:
      - us-east-1
  azure:
    use_cli: true  # Use Azure CLI credentials
  gcp:
    use_application_default: true  # Use gcloud auth

security:
  enable_auth: false  # Simplified auth for development
  jwt_secret: "development-secret-key"
  session_timeout: 24h

database:
  type: "sqlite"
  database: "driftmgr.db"
  
logging:
  level: "debug"
  format: "text"
  output: "stdout"
  colorize: true

monitoring:
  metrics:
    enabled: false
  health:
    enabled: true
    path: "/health"
  tracing:
    enabled: false

rate_limiting:
  enabled: false

notifications:
  email:
    enabled: false

remediation:
  enabled: true
  dry_run: true  # Always dry-run in development
  require_approval: false

# Development-specific features
features:
  auto_discovery: true
  drift_detection: true
  cost_analysis: true
  compliance_scanning: false
  terraform_import: true
  export_reports: true
  debug_endpoints: true  # Enable debug endpoints