# Production Configuration for DriftMgr
# This configuration file should be used in production environments

server:
  port: 8080
  host: "0.0.0.0"  # Allow external connections
  tls:
    enabled: true
    cert_file: "/etc/driftmgr/certs/server.crt"
    key_file: "/etc/driftmgr/certs/server.key"

discovery:
  timeout: 30m
  concurrency_limit: 20
  batch_size: 100
  retry_attempts: 3
  retry_delay: 5s
  enable_caching: true
  cache_ttl: 5m
  cache_max_size: 1000
  api_timeout: 2m

providers:
  aws:
    use_iam_role: true  # Use IAM role instead of hardcoded credentials
    regions:
      - us-east-1
      - us-west-2
      - eu-west-1
  azure:
    use_managed_identity: true  # Use Azure Managed Identity
    subscription_id: "${AZURE_SUBSCRIPTION_ID}"
  gcp:
    use_service_account: true
    project_id: "${GCP_PROJECT_ID}"

security:
  enable_auth: true
  jwt_secret: "${JWT_SECRET}"  # Must be set via environment variable
  session_timeout: 24h
  max_login_attempts: 5
  lockout_duration: 15m
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special: true
  encryption:
    enabled: true
    key: "${ENCRYPTION_KEY}"  # Must be set via environment variable

database:
  type: "postgres"  # Use PostgreSQL in production
  host: "${DB_HOST}"
  port: 5432
  database: "driftmgr"
  username: "${DB_USER}"
  password: "${DB_PASSWORD}"
  ssl_mode: "require"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 1h

logging:
  level: "info"
  format: "json"  # JSON format for log aggregation
  output: "stdout"
  file:
    enabled: true
    path: "/var/log/driftmgr/app.log"
    max_size: 100  # MB
    max_backups: 7
    max_age: 30  # days

monitoring:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
  health:
    enabled: true
    path: "/health"
    liveness_path: "/health/live"
    readiness_path: "/health/ready"
  tracing:
    enabled: true
    provider: "jaeger"
    endpoint: "${JAEGER_ENDPOINT}"
    sample_rate: 0.1

rate_limiting:
  enabled: true
  requests_per_second: 100
  burst: 200

notifications:
  email:
    enabled: true
    smtp_host: "${SMTP_HOST}"
    smtp_port: 587
    smtp_user: "${SMTP_USER}"
    smtp_password: "${SMTP_PASSWORD}"
    from_address: "driftmgr@example.com"
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
  pagerduty:
    enabled: false
    integration_key: "${PAGERDUTY_KEY}"

remediation:
  enabled: false  # Disabled by default for safety
  dry_run: true
  require_approval: true
  max_parallel_remediations: 5

# Feature flags
features:
  auto_discovery: true
  drift_detection: true
  cost_analysis: true
  compliance_scanning: true
  terraform_import: true
  export_reports: true