# Prometheus configuration for DriftMgr monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- "rules/*.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
# DriftMgr API server metrics
- job_name: 'driftmgr-api'
  static_configs:
  - targets: [ 'api:8080' ]
  metrics_path: '/api/v1/metrics'
  scrape_interval: 10s
  scrape_timeout: 5s

# DriftMgr web dashboard metrics
- job_name: 'driftmgr-web'
  static_configs:
  - targets: [ 'web:3000' ]
  metrics_path: '/metrics'
  scrape_interval: 15s

# PostgreSQL metrics
- job_name: 'postgres'
  static_configs:
  - targets: [ 'postgres:5432' ]
  scrape_interval: 30s

# Redis metrics
- job_name: 'redis'
  static_configs:
  - targets: [ 'redis:6379' ]
  scrape_interval: 30s

# Node exporter for system metrics
- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
  scrape_interval: 15s

# Prometheus self-monitoring
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]
  scrape_interval: 15s

# Grafana metrics
- job_name: 'grafana'
  static_configs:
  - targets: [ 'grafana:3000' ]
  metrics_path: '/metrics'
  scrape_interval: 30s

# Jaeger metrics
- job_name: 'jaeger'
  static_configs:
  - targets: [ 'jaeger:14269' ]
  metrics_path: '/metrics'
  scrape_interval: 30s

# Elasticsearch metrics
- job_name: 'elasticsearch'
  static_configs:
  - targets: [ 'elasticsearch:9200' ]
  metrics_path: '/_prometheus/metrics'
  scrape_interval: 30s

# Kibana metrics
- job_name: 'kibana'
  static_configs:
  - targets: [ 'kibana:5601' ]
  metrics_path: '/api/status'
  scrape_interval: 30s

# Logstash metrics
- job_name: 'logstash'
  static_configs:
  - targets: [ 'logstash:9600' ]
  metrics_path: '/_node/stats'
  scrape_interval: 30s

# MinIO metrics
- job_name: 'minio'
  static_configs:
  - targets: [ 'minio:9000' ]
  metrics_path: '/minio/v2/metrics/cluster'
  scrape_interval: 30s

# Nginx metrics
- job_name: 'nginx'
  static_configs:
  - targets: [ 'nginx:80' ]
  metrics_path: '/nginx_status'
  scrape_interval: 30s
