global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'driftmgr'
    static_configs:
      - targets: ['driftmgr:8080']
        labels:
          service: 'driftmgr'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']