# Staging Configuration for DriftMgr
# This configuration is for staging/pre-production environments

server:
  port: 8080
  host: "0.0.0.0"
  tls:
    enabled: true
    cert_file: "/etc/driftmgr/certs/server.crt"
    key_file: "/etc/driftmgr/certs/server.key"

discovery:
  timeout: 15m
  concurrency_limit: 10
  batch_size: 75
  retry_attempts: 3
  retry_delay: 3s
  enable_caching: true
  cache_ttl: 3m
  cache_max_size: 500
  api_timeout: 1m

providers:
  aws:
    use_iam_role: true
    regions:
      - us-east-1
      - us-west-2
  azure:
    use_managed_identity: true
    subscription_id: "${AZURE_SUBSCRIPTION_ID}"
  gcp:
    use_service_account: true
    project_id: "${GCP_PROJECT_ID}"

security:
  enable_auth: true
  jwt_secret: "${JWT_SECRET}"
  session_timeout: 12h
  max_login_attempts: 5
  lockout_duration: 10m
  password_policy:
    min_length: 10
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special: false

database:
  type: "postgres"
  host: "${DB_HOST}"
  port: 5432
  database: "driftmgr_staging"
  username: "${DB_USER}"
  password: "${DB_PASSWORD}"
  ssl_mode: "prefer"
  max_open_conns: 15
  max_idle_conns: 5
  conn_max_lifetime: 30m

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: true
    path: "/var/log/driftmgr/app.log"
    max_size: 50
    max_backups: 5
    max_age: 14

monitoring:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
  health:
    enabled: true
    path: "/health"
    liveness_path: "/health/live"
    readiness_path: "/health/ready"
  tracing:
    enabled: true
    provider: "jaeger"
    endpoint: "${JAEGER_ENDPOINT}"
    sample_rate: 0.5

rate_limiting:
  enabled: true
  requests_per_second: 50
  burst: 100

notifications:
  email:
    enabled: true
    smtp_host: "${SMTP_HOST}"
    smtp_port: 587
    smtp_user: "${SMTP_USER}"
    smtp_password: "${SMTP_PASSWORD}"
    from_address: "driftmgr-staging@example.com"
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"

remediation:
  enabled: true
  dry_run: true
  require_approval: true
  max_parallel_remediations: 3

# Staging features (testing new features)
features:
  auto_discovery: true
  drift_detection: true
  cost_analysis: true
  compliance_scanning: true
  terraform_import: true
  export_reports: true
  experimental_features: true  # Test new features in staging