package dependencies

// AWSResourceDependencies maps AWS resource types to their dependencies
var AWSResourceDependencies = map[string][]string{
	// Complex resources with dependencies
	"eks_cluster":        {"eks_cluster", "autoscaling_group", "iam_role", "security_group", "subnet", "vpc"},
	"ecs_cluster":        {"ecs_cluster", "ecs_service", "iam_role", "security_group", "subnet", "vpc"},
	"rds_instance":       {"rds_instance", "rds_snapshot", "security_group", "subnet", "vpc"},
	"vpc":               {"vpc", "nat_gateway", "internet_gateway", "route_table", "subnet", "security_group"},
	"ec2_instance":      {"ec2_instance", "ebs_volume", "security_group", "iam_role"},
	"elasticache_cluster": {"elasticache_cluster", "security_group", "subnet", "vpc"},
	"load_balancer":     {"load_balancer", "target_group", "security_group", "subnet", "vpc"},
	"lambda_function":   {"lambda_function", "iam_role", "cloudwatch_log_group"},
	"api_gateway":       {"api_gateway", "lambda_function", "iam_role", "cloudwatch_log_group"},
	"cloudfront_distribution": {"cloudfront_distribution", "s3_bucket", "iam_role"},
	"elasticsearch_domain": {"elasticsearch_domain", "security_group", "subnet", "vpc"},
	"redshift_cluster":  {"redshift_cluster", "security_group", "subnet", "vpc", "iam_role"},
	"emr_cluster":       {"emr_cluster", "ec2_instance", "security_group", "subnet", "vpc", "iam_role"},
	"msk_cluster":       {"msk_cluster", "security_group", "subnet", "vpc"},
	"opensearch_domain": {"opensearch_domain", "security_group", "subnet", "vpc"},
	"neptune_cluster":   {"neptune_cluster", "security_group", "subnet", "vpc"},
	"docdb_cluster":     {"docdb_cluster", "security_group", "subnet", "vpc"},
	"aurora_cluster":    {"aurora_cluster", "rds_instance", "security_group", "subnet", "vpc"},
	"elastic_beanstalk_environment": {"elastic_beanstalk_environment", "ec2_instance", "security_group", "subnet", "vpc", "iam_role"},
	"ecs_service":       {"ecs_service", "ecs_task_definition", "iam_role", "security_group"},
	"ecs_task_definition": {"ecs_task_definition", "iam_role"},
	"autoscaling_group": {"autoscaling_group", "launch_template", "iam_role"},
	"launch_template":   {"launch_template", "iam_role"},
	"target_group":      {"target_group", "load_balancer"},
	"nat_gateway":       {"nat_gateway", "subnet", "vpc"},
	"internet_gateway":  {"internet_gateway", "vpc"},
	"route_table":       {"route_table", "vpc"},
	"subnet":            {"subnet", "vpc"},
	"security_group":    {"security_group", "vpc"},
	"iam_role":          {"iam_role", "iam_policy"},
	"iam_policy":        {"iam_policy"},
	"iam_user":          {"iam_user", "iam_access_key"},
	"iam_group":         {"iam_group"},
	"cloudwatch_log_group": {"cloudwatch_log_group"},
	"cloudwatch_alarm":  {"cloudwatch_alarm"},
	"cloudwatch_dashboard": {"cloudwatch_dashboard"},
	"sns_topic":         {"sns_topic", "sns_subscription"},
	"sns_subscription":  {"sns_subscription"},
	"sqs_queue":         {"sqs_queue"},
	"dynamodb_table":    {"dynamodb_table"},
	"s3_bucket":         {"s3_bucket"},
	"kms_key":           {"kms_key"},
	"secretsmanager_secret": {"secretsmanager_secret"},
	"ssm_parameter":     {"ssm_parameter"},
	"ecr_repository":    {"ecr_repository"},
	"ecr_image":         {"ecr_image"},
	"codecommit_repository": {"codecommit_repository"},
	"codepipeline":      {"codepipeline", "codebuild_project"},
	"codebuild_project": {"codebuild_project", "iam_role"},
	"codedeploy_application": {"codedeploy_application", "codedeploy_deployment_group"},
	"codedeploy_deployment_group": {"codedeploy_deployment_group"},
	"cloudformation_stack": {"cloudformation_stack"},
	"route53_zone":      {"route53_zone", "route53_record"},
	"route53_record":    {"route53_record"},
	"acm_certificate":   {"acm_certificate"},
	"waf_web_acl":       {"waf_web_acl"},
	"wafv2_web_acl":     {"wafv2_web_acl"},
	"shield_protection": {"shield_protection"},
	"guardduty_detector": {"guardduty_detector"},
	"config_recorder":   {"config_recorder"},
	"config_rule":       {"config_rule"},
	"backup_vault":      {"backup_vault", "backup_plan"},
	"backup_plan":       {"backup_plan"},
	"glue_job":          {"glue_job", "iam_role"},
	"glue_crawler":      {"glue_crawler", "iam_role"},
	"athena_workgroup":  {"athena_workgroup"},
	"quicksight_dashboard": {"quicksight_dashboard"},
	"sagemaker_notebook_instance": {"sagemaker_notebook_instance", "iam_role", "security_group", "subnet", "vpc"},
	"sagemaker_endpoint": {"sagemaker_endpoint", "sagemaker_model"},
	"sagemaker_model":   {"sagemaker_model"},
	"transit_gateway":   {"transit_gateway", "transit_gateway_attachment"},
	"transit_gateway_attachment": {"transit_gateway_attachment"},
	"vpn_connection":    {"vpn_connection", "vpn_gateway"},
	"vpn_gateway":       {"vpn_gateway"},
	"direct_connect_connection": {"direct_connect_connection"},
	"direct_connect_gateway": {"direct_connect_gateway"},
	"appsync_graphql_api": {"appsync_graphql_api", "iam_role"},
	"amplify_app":       {"amplify_app"},
	"cognito_user_pool": {"cognito_user_pool"},
	"cognito_identity_pool": {"cognito_identity_pool", "iam_role"},
	"pinpoint_app":      {"pinpoint_app"},
	"s3_object":         {"s3_object"},
	"ebs_volume":        {"ebs_volume"},
	"ebs_snapshot":      {"ebs_snapshot"},
	"ami":               {"ami"},
	"elastic_ip":        {"elastic_ip"},
	"network_interface": {"network_interface"},
	"placement_group":   {"placement_group"},
	"key_pair":          {"key_pair"},
	"customer_gateway":  {"customer_gateway"},
	"dhcp_options":      {"dhcp_options"},
	"endpoint":          {"endpoint", "vpc"},
	"flow_log":          {"flow_log"},
	"network_acl":       {"network_acl", "vpc"},
	"peering_connection": {"peering_connection"},
	"transit_gateway_route_table": {"transit_gateway_route_table"},
	"transit_gateway_vpc_attachment": {"transit_gateway_vpc_attachment"},
}

// AWSComplexResources lists AWS resources that have dependencies
var AWSComplexResources = map[string]bool{
	"eks_cluster": true, "ecs_cluster": true, "rds_instance": true, "vpc": true,
	"ec2_instance": true, "elasticache_cluster": true, "load_balancer": true,
	"lambda_function": true, "api_gateway": true, "cloudfront_distribution": true,
	"elasticsearch_domain": true, "redshift_cluster": true, "emr_cluster": true,
	"msk_cluster": true, "opensearch_domain": true, "neptune_cluster": true,
	"docdb_cluster": true, "aurora_cluster": true, "elastic_beanstalk_environment": true,
	"ecs_service": true, "ecs_task_definition": true, "autoscaling_group": true,
	"launch_template": true, "target_group": true, "nat_gateway": true,
	"internet_gateway": true, "route_table": true, "subnet": true, "security_group": true,
	"iam_role": true, "iam_policy": true, "iam_user": true, "iam_group": true,
	"sns_topic": true, "sns_subscription": true, "codepipeline": true,
	"codebuild_project": true, "codedeploy_application": true, "codedeploy_deployment_group": true,
	"route53_zone": true, "route53_record": true, "backup_vault": true, "backup_plan": true,
	"glue_job": true, "glue_crawler": true, "sagemaker_notebook_instance": true,
	"sagemaker_endpoint": true, "sagemaker_model": true, "transit_gateway": true,
	"transit_gateway_attachment": true, "vpn_connection": true, "vpn_gateway": true,
	"appsync_graphql_api": true, "cognito_identity_pool": true, "endpoint": true,
	"network_acl": true, "transit_gateway_route_table": true, "transit_gateway_vpc_attachment": true,
}
