package dependencies

// AzureResourceDependencies maps Azure resource types to their dependencies
var AzureResourceDependencies = map[string][]string{
	// Compute & Container Services
	"aks_cluster":               {"aks_cluster", "vmss", "managed_identity", "nsg", "subnet", "vnet"},
	"acr_registry":              {"acr_registry", "managed_identity"},
	"container_instance":        {"container_instance", "managed_identity"},
	"vm":                        {"vm", "disk", "nsg", "subnet", "vnet", "managed_identity"},
	"vmss":                      {"vmss", "disk", "nsg", "subnet", "vnet", "managed_identity"},
	"app_service_plan":          {"app_service_plan", "app_service", "managed_identity"},
	"app_service":               {"app_service", "managed_identity", "app_service_plan"},
	"function_app":              {"function_app", "managed_identity", "app_service_plan"},
	"static_web_app":            {"static_web_app", "managed_identity"},
	"spring_cloud_service":      {"spring_cloud_service", "spring_cloud_app", "managed_identity"},
	"spring_cloud_app":          {"spring_cloud_app", "managed_identity"},
	"service_fabric_cluster":    {"service_fabric_cluster", "managed_identity", "nsg", "subnet", "vnet"},
	"batch_account":             {"batch_account", "managed_identity"},
	"batch_pool":                {"batch_pool", "managed_identity"},
	"cloud_service":             {"cloud_service", "managed_identity", "nsg", "subnet", "vnet"},
	"availability_set":          {"availability_set"},
	"proximity_placement_group": {"proximity_placement_group"},
	"dedicated_host":            {"dedicated_host"},
	"dedicated_host_group":      {"dedicated_host_group"},

	// Database Services
	"sql_server":               {"sql_server", "sql_database", "managed_identity"},
	"sql_database":             {"sql_database", "managed_identity"},
	"sql_managed_instance":     {"sql_managed_instance", "managed_identity", "subnet", "vnet"},
	"cosmos_db_account":        {"cosmos_db_account", "cosmos_db_database", "managed_identity"},
	"cosmos_db_database":       {"cosmos_db_database"},
	"mysql_server":             {"mysql_server", "mysql_database", "managed_identity"},
	"mysql_database":           {"mysql_database"},
	"postgresql_server":        {"postgresql_server", "postgresql_database", "managed_identity"},
	"postgresql_database":      {"postgresql_database"},
	"redis_cache":              {"redis_cache", "managed_identity", "subnet", "vnet"},
	"synapse_workspace":        {"synapse_workspace", "managed_identity", "subnet", "vnet"},
	"synapse_spark_pool":       {"synapse_spark_pool", "managed_identity"},
	"synapse_sql_pool":         {"synapse_sql_pool", "managed_identity"},
	"data_factory":             {"data_factory", "managed_identity"},
	"data_lake_storage":        {"data_lake_storage", "managed_identity"},
	"data_lake_analytics":      {"data_lake_analytics", "managed_identity"},
	"event_hubs_namespace":     {"event_hubs_namespace", "event_hub", "managed_identity"},
	"event_hub":                {"event_hub"},
	"service_bus_namespace":    {"service_bus_namespace", "service_bus_queue", "managed_identity"},
	"service_bus_queue":        {"service_bus_queue"},
	"service_bus_topic":        {"service_bus_topic", "service_bus_subscription"},
	"service_bus_subscription": {"service_bus_subscription"},

	// Networking & Load Balancing
	"vnet":                     {"vnet", "subnet", "nsg", "route_table", "nat_gateway", "vnet_gateway"},
	"subnet":                   {"subnet", "vnet"},
	"nsg":                      {"nsg", "vnet"},
	"route_table":              {"route_table", "vnet"},
	"nat_gateway":              {"nat_gateway", "subnet", "vnet"},
	"vnet_gateway":             {"vnet_gateway", "subnet", "vnet"},
	"express_route_circuit":    {"express_route_circuit", "express_route_peering"},
	"express_route_peering":    {"express_route_peering"},
	"vpn_gateway":              {"vpn_gateway", "subnet", "vnet"},
	"vpn_connection":           {"vpn_connection", "vpn_gateway"},
	"load_balancer":            {"load_balancer", "backend_pool", "nsg", "subnet", "vnet"},
	"application_gateway":      {"application_gateway", "backend_pool", "nsg", "subnet", "vnet"},
	"front_door":               {"front_door", "backend_pool"},
	"cdn_profile":              {"cdn_profile", "cdn_endpoint"},
	"cdn_endpoint":             {"cdn_endpoint"},
	"traffic_manager_profile":  {"traffic_manager_profile", "traffic_manager_endpoint"},
	"traffic_manager_endpoint": {"traffic_manager_endpoint"},
	"private_link_service":     {"private_link_service", "subnet", "vnet"},
	"private_endpoint":         {"private_endpoint", "subnet", "vnet"},
	"dns_zone":                 {"dns_zone", "dns_record"},
	"dns_record":               {"dns_record"},
	"private_dns_zone":         {"private_dns_zone", "private_dns_record"},
	"private_dns_record":       {"private_dns_record"},
	"firewall":                 {"firewall", "subnet", "vnet"},
	"firewall_policy":          {"firewall_policy"},
	"bastion_host":             {"bastion_host", "subnet", "vnet"},
	"point_to_site_vpn":        {"point_to_site_vpn", "vpn_gateway"},
	"site_to_site_vpn":         {"site_to_site_vpn", "vpn_gateway"},
	"vnet_peering":             {"vnet_peering"},
	"network_watcher":          {"network_watcher"},

	// Storage Services
	"storage_account":         {"storage_account", "managed_identity"},
	"storage_container":       {"storage_container"},
	"storage_blob":            {"storage_blob"},
	"storage_file_share":      {"storage_file_share"},
	"storage_table":           {"storage_table"},
	"storage_queue":           {"storage_queue"},
	"disk":                    {"disk"},
	"disk_snapshot":           {"disk_snapshot"},
	"managed_disk":            {"managed_disk"},
	"backup_vault":            {"backup_vault", "backup_policy"},
	"backup_policy":           {"backup_policy"},
	"recovery_services_vault": {"recovery_services_vault", "backup_policy"},
	"site_recovery_vault":     {"site_recovery_vault"},

	// Identity & Security
	"managed_identity":           {"managed_identity"},
	"key_vault":                  {"key_vault", "managed_identity"},
	"key_vault_key":              {"key_vault_key"},
	"key_vault_secret":           {"key_vault_secret"},
	"key_vault_certificate":      {"key_vault_certificate"},
	"app_registration":           {"app_registration"},
	"service_principal":          {"service_principal"},
	"user_assigned_identity":     {"user_assigned_identity"},
	"system_assigned_identity":   {"system_assigned_identity"},
	"role_assignment":            {"role_assignment"},
	"role_definition":            {"role_definition"},
	"policy_assignment":          {"policy_assignment"},
	"policy_definition":          {"policy_definition"},
	"policy_set_definition":      {"policy_set_definition"},
	"security_center":            {"security_center"},
	"defender_plan":              {"defender_plan"},
	"sentinel_workspace":         {"sentinel_workspace"},
	"log_analytics_workspace":    {"log_analytics_workspace"},
	"application_insights":       {"application_insights"},
	"monitor_action_group":       {"monitor_action_group"},
	"monitor_alert_rule":         {"monitor_alert_rule"},
	"monitor_diagnostic_setting": {"monitor_diagnostic_setting"},
	"monitor_log_profile":        {"monitor_log_profile"},
	"monitor_metric_alert":       {"monitor_metric_alert"},
	"monitor_activity_log_alert": {"monitor_activity_log_alert"},

	// AI & Machine Learning
	"machine_learning_workspace": {"machine_learning_workspace", "managed_identity"},
	"machine_learning_compute":   {"machine_learning_compute", "managed_identity"},
	"cognitive_service":          {"cognitive_service", "managed_identity"},
	"bot_service":                {"bot_service", "managed_identity"},
	"search_service":             {"search_service", "managed_identity"},
	"openai_account":             {"openai_account", "managed_identity"},
	"computer_vision":            {"computer_vision", "managed_identity"},
	"face_api":                   {"face_api", "managed_identity"},
	"text_analytics":             {"text_analytics", "managed_identity"},
	"speech_service":             {"speech_service", "managed_identity"},
	"translator":                 {"translator", "managed_identity"},
	"form_recognizer":            {"form_recognizer", "managed_identity"},
	"personalizer":               {"personalizer", "managed_identity"},
	"anomaly_detector":           {"anomaly_detector", "managed_identity"},
	"content_moderator":          {"content_moderator", "managed_identity"},
	"custom_vision":              {"custom_vision", "managed_identity"},
	"immersive_reader":           {"immersive_reader", "managed_identity"},
	"metrics_advisor":            {"metrics_advisor", "managed_identity"},
	"video_indexer":              {"video_indexer", "managed_identity"},

	// IoT & Edge Services
	"iot_hub":                     {"iot_hub", "managed_identity"},
	"iot_edge_device":             {"iot_edge_device"},
	"device_provisioning_service": {"device_provisioning_service", "managed_identity"},
	"digital_twins_instance":      {"digital_twins_instance", "managed_identity"},
	"time_series_insights":        {"time_series_insights", "managed_identity"},
	"sphere_catalog":              {"sphere_catalog", "managed_identity"},
	"sphere_product":              {"sphere_product"},
	"sphere_device_group":         {"sphere_device_group"},
	"sphere_deployment":           {"sphere_deployment"},

	// Developer Tools & DevOps
	"devops_organization":                                             {"devops_organization"},
	"devops_project":                                                  {"devops_project"},
	"devops_repository":                                               {"devops_repository"},
	"devops_pipeline":                                                 {"devops_pipeline"},
	"devops_agent_pool":                                               {"devops_agent_pool"},
	"api_management":                                                  {"api_management", "managed_identity"},
	"api_management_api":                                              {"api_management_api"},
	"api_management_product":                                          {"api_management_product"},
	"api_management_subscription":                                     {"api_management_subscription"},
	"signalr_service":                                                 {"signalr_service", "managed_identity"},
	"web_pubsub_service":                                              {"web_pubsub_service", "managed_identity"},
	"notification_hub":                                                {"notification_hub", "managed_identity"},
	"notification_hub_namespace":                                      {"notification_hub_namespace", "managed_identity"},
	"media_services":                                                  {"media_services", "managed_identity"},
	"media_live_event":                                                {"media_live_event"},
	"media_streaming_endpoint":                                        {"media_streaming_endpoint"},
	"media_transform":                                                 {"media_transform"},
	"media_job":                                                       {"media_job"},
	"media_asset":                                                     {"media_asset"},
	"media_content_key_policy":                                        {"media_content_key_policy"},
	"media_streaming_policy":                                          {"media_streaming_policy"},
	"media_asset_filter":                                              {"media_asset_filter"},
	"media_account_filter":                                            {"media_account_filter"},
	"media_live_output":                                               {"media_live_output"},
	"media_live_event_input":                                          {"media_live_event_input"},
	"media_live_event_output":                                         {"media_live_event_output"},
	"media_live_event_encoding":                                       {"media_live_event_encoding"},
	"media_live_event_preview":                                        {"media_live_event_preview"},
	"media_live_event_input_track":                                    {"media_live_event_input_track"},
	"media_live_event_output_track":                                   {"media_live_event_output_track"},
	"media_live_event_encoding_track":                                 {"media_live_event_encoding_track"},
	"media_live_event_preview_track":                                  {"media_live_event_preview_track"},
	"media_live_event_input_track_selection":                          {"media_live_event_input_track_selection"},
	"media_live_event_output_track_selection":                         {"media_live_event_output_track_selection"},
	"media_live_event_encoding_track_selection":                       {"media_live_event_encoding_track_selection"},
	"media_live_event_preview_track_selection":                        {"media_live_event_preview_track_selection"},
	"media_live_event_input_track_descriptor":                         {"media_live_event_input_track_descriptor"},
	"media_live_event_output_track_descriptor":                        {"media_live_event_output_track_descriptor"},
	"media_live_event_encoding_track_descriptor":                      {"media_live_event_encoding_track_descriptor"},
	"media_live_event_preview_track_descriptor":                       {"media_live_event_preview_track_descriptor"},
	"media_live_event_input_track_descriptor_selection":               {"media_live_event_input_track_descriptor_selection"},
	"media_live_event_output_track_descriptor_selection":              {"media_live_event_output_track_descriptor_selection"},
	"media_live_event_encoding_track_descriptor_selection":            {"media_live_event_encoding_track_descriptor_selection"},
	"media_live_event_preview_track_descriptor_selection":             {"media_live_event_preview_track_descriptor_selection"},
	"media_live_event_input_track_descriptor_descriptor":              {"media_live_event_input_track_descriptor_descriptor"},
	"media_live_event_output_track_descriptor_descriptor":             {"media_live_event_output_track_descriptor_descriptor"},
	"media_live_event_encoding_track_descriptor_descriptor":           {"media_live_event_encoding_track_descriptor_descriptor"},
	"media_live_event_preview_track_descriptor_descriptor":            {"media_live_event_preview_track_descriptor_descriptor"},
	"media_live_event_input_track_descriptor_descriptor_selection":    {"media_live_event_input_track_descriptor_descriptor_selection"},
	"media_live_event_output_track_descriptor_descriptor_selection":   {"media_live_event_output_track_descriptor_descriptor_selection"},
	"media_live_event_encoding_track_descriptor_descriptor_selection": {"media_live_event_encoding_track_descriptor_descriptor_selection"},
	"media_live_event_preview_track_descriptor_descriptor_selection":  {"media_live_event_preview_track_descriptor_descriptor_selection"},
}

// AzureComplexResources lists Azure resources that have dependencies
var AzureComplexResources = map[string]bool{
	"aks_cluster": true, "acr_registry": true, "container_instance": true, "vm": true,
	"vmss": true, "app_service_plan": true, "app_service": true, "function_app": true,
	"static_web_app": true, "spring_cloud_service": true, "spring_cloud_app": true,
	"service_fabric_cluster": true, "batch_account": true, "batch_pool": true,
	"cloud_service": true, "sql_server": true, "sql_database": true, "sql_managed_instance": true,
	"cosmos_db_account": true, "cosmos_db_database": true, "mysql_server": true,
	"mysql_database": true, "postgresql_server": true, "postgresql_database": true,
	"redis_cache": true, "synapse_workspace": true, "synapse_spark_pool": true,
	"synapse_sql_pool": true, "data_factory": true, "data_lake_storage": true,
	"data_lake_analytics": true, "event_hubs_namespace": true, "event_hub": true,
	"service_bus_namespace": true, "service_bus_queue": true, "service_bus_topic": true,
	"service_bus_subscription": true, "vnet": true, "subnet": true, "nsg": true,
	"route_table": true, "nat_gateway": true, "vnet_gateway": true, "express_route_circuit": true,
	"express_route_peering": true, "vpn_gateway": true, "vpn_connection": true,
	"load_balancer": true, "application_gateway": true, "front_door": true,
	"cdn_profile": true, "cdn_endpoint": true, "traffic_manager_profile": true,
	"traffic_manager_endpoint": true, "private_link_service": true, "private_endpoint": true,
	"dns_zone": true, "dns_record": true, "private_dns_zone": true, "private_dns_record": true,
	"firewall": true, "firewall_policy": true, "bastion_host": true, "point_to_site_vpn": true,
	"site_to_site_vpn": true, "vnet_peering": true, "network_watcher": true,
	"storage_account": true, "storage_container": true, "storage_blob": true,
	"storage_file_share": true, "storage_table": true, "storage_queue": true,
	"disk": true, "disk_snapshot": true, "managed_disk": true, "backup_vault": true,
	"backup_policy": true, "recovery_services_vault": true, "site_recovery_vault": true,
	"managed_identity": true, "key_vault": true, "key_vault_key": true, "key_vault_secret": true,
	"key_vault_certificate": true, "app_registration": true, "service_principal": true,
	"user_assigned_identity": true, "system_assigned_identity": true, "role_assignment": true,
	"role_definition": true, "policy_assignment": true, "policy_definition": true,
	"policy_set_definition": true, "security_center": true, "defender_plan": true,
	"sentinel_workspace": true, "log_analytics_workspace": true, "application_insights": true,
	"monitor_action_group": true, "monitor_alert_rule": true, "monitor_diagnostic_setting": true,
	"monitor_log_profile": true, "monitor_metric_alert": true, "monitor_activity_log_alert": true,
	"machine_learning_workspace": true, "machine_learning_compute": true, "cognitive_service": true,
	"bot_service": true, "search_service": true, "openai_account": true, "computer_vision": true,
	"face_api": true, "text_analytics": true, "speech_service": true, "translator": true,
	"form_recognizer": true, "personalizer": true, "anomaly_detector": true,
	"content_moderator": true, "custom_vision": true, "immersive_reader": true,
	"metrics_advisor": true, "video_indexer": true, "iot_hub": true, "iot_edge_device": true,
	"device_provisioning_service": true, "digital_twins_instance": true, "time_series_insights": true,
	"sphere_catalog": true, "sphere_product": true, "sphere_device_group": true,
	"sphere_deployment": true, "devops_organization": true, "devops_project": true,
	"devops_repository": true, "devops_pipeline": true, "devops_agent_pool": true,
	"api_management": true, "api_management_api": true, "api_management_product": true,
	"api_management_subscription": true, "signalr_service": true, "web_pubsub_service": true,
	"notification_hub": true, "notification_hub_namespace": true, "media_services": true,
	"media_live_event": true, "media_streaming_endpoint": true, "media_transform": true,
	"media_job": true, "media_asset": true, "media_content_key_policy": true,
	"media_streaming_policy": true, "media_asset_filter": true, "media_account_filter": true,
	"media_live_output": true, "media_live_event_input": true, "media_live_event_output": true,
	"media_live_event_encoding": true, "media_live_event_preview": true, "media_live_event_input_track": true,
	"media_live_event_output_track": true, "media_live_event_encoding_track": true,
	"media_live_event_preview_track": true, "media_live_event_input_track_selection": true,
	"media_live_event_output_track_selection": true, "media_live_event_encoding_track_selection": true,
	"media_live_event_preview_track_selection": true, "media_live_event_input_track_descriptor": true,
	"media_live_event_output_track_descriptor": true, "media_live_event_encoding_track_descriptor": true,
	"media_live_event_preview_track_descriptor": true, "media_live_event_input_track_descriptor_selection": true,
	"media_live_event_output_track_descriptor_selection": true, "media_live_event_encoding_track_descriptor_selection": true,
	"media_live_event_preview_track_descriptor_selection": true, "media_live_event_input_track_descriptor_descriptor": true,
	"media_live_event_output_track_descriptor_descriptor": true, "media_live_event_encoding_track_descriptor_descriptor": true,
	"media_live_event_preview_track_descriptor_descriptor": true, "media_live_event_input_track_descriptor_descriptor_selection": true,
	"media_live_event_output_track_descriptor_descriptor_selection": true, "media_live_event_encoding_track_descriptor_descriptor_selection": true,
	"media_live_event_preview_track_descriptor_descriptor_selection": true,
}
