name: Phase 3 - Enhanced State Management Validation

on:
  push:
    paths: 
      - 'internal/api/state/**'
      - 'internal/business/state/**'
      - 'internal/storage/state/**'
      - 'tests/api/state/**'
      - 'tests/integration/state/**'
  pull_request:
    paths: 
      - 'internal/api/state/**'
      - 'internal/business/state/**'
      - 'internal/storage/state/**'
      - 'tests/api/state/**'
      - 'tests/integration/state/**'

env:
  GO_VERSION: '1.21'
  COVERAGE_THRESHOLD: 90

jobs:
  # Code Quality Checks
  lint:
    name: Code Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run gofmt
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  # Unit Tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: |
          go test ./internal/api/state/... -v -race -coverprofile=coverage.out -covermode=atomic
          go test ./internal/business/state/... -v -race -coverprofile=coverage2.out -covermode=atomic
          go test ./internal/storage/state/... -v -race -coverprofile=coverage3.out -covermode=atomic

      - name: Merge coverage reports
        run: |
          echo "mode: atomic" > coverage_merged.out
          grep -h -v "^mode:" coverage.out coverage2.out coverage3.out >> coverage_merged.out

      - name: Check coverage threshold
        run: |
          coverage=$(go tool cover -func=coverage_merged.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Coverage: ${coverage}%"
          if (( $(echo "$coverage < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Coverage ${coverage}% is below threshold ${COVERAGE_THRESHOLD}%"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage_merged.out
          flags: phase3
          name: phase3-coverage

  # State Management Tests
  state-tests:
    name: State Management Tests
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: driftmgr_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Run state management tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/driftmgr_test?sslmode=disable
        run: |
          go test ./internal/business/state/... -v -race

  # API Integration Tests
  api-tests:
    name: API Integration Tests
    runs-on: ubuntu-latest
    needs: [unit-tests, state-tests]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: driftmgr_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Run API tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/driftmgr_test?sslmode=disable
          API_PORT: 8080
        run: |
          go test ./tests/api/state/... -v -timeout=15m

  # Performance Tests
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: api-tests
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: driftmgr_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Run performance tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/driftmgr_test?sslmode=disable
        run: |
          go test ./tests/performance/state/... -v -timeout=10m

  # Security Tests
  security-tests:
    name: Security Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Gosec Security Scanner
        run: |
          go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest
          gosec -fmt sarif -out gosec.sarif ./internal/api/state/... ./internal/business/state/... ./internal/storage/state/...

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gosec.sarif

  # Build and Package
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: [unit-tests, state-tests, api-tests, performance-tests, security-tests]
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -ldflags="-s -w" -o driftmgr-${{ matrix.os }}-${{ matrix.arch }} ./cmd/server

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: driftmgr-phase3-${{ matrix.os }}-${{ matrix.arch }}
          path: driftmgr-${{ matrix.os }}-${{ matrix.arch }}

  # Documentation Tests
  docs-tests:
    name: Documentation Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Check API documentation
        run: |
          go run ./scripts/check-api-docs.go --phase=3

      - name: Generate API documentation
        run: |
          go run ./scripts/generate-api-docs.go --phase=3

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: phase3-api-docs
          path: docs/api/phase3/

  # Phase 3 Validation Summary
  phase3-summary:
    name: Phase 3 Validation Summary
    runs-on: ubuntu-latest
    needs: [build, docs-tests]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create validation report
        run: |
          echo "# Phase 3 Validation Report" > validation-report.md
          echo "" >> validation-report.md
          echo "## Test Results" >> validation-report.md
          echo "- Unit Tests: ${{ needs.unit-tests.result }}" >> validation-report.md
          echo "- State Tests: ${{ needs.state-tests.result }}" >> validation-report.md
          echo "- API Tests: ${{ needs.api-tests.result }}" >> validation-report.md
          echo "- Performance Tests: ${{ needs.performance-tests.result }}" >> validation-report.md
          echo "- Security Tests: ${{ needs.security-tests.result }}" >> validation-report.md
          echo "- Build: ${{ needs.build.result }}" >> validation-report.md
          echo "- Documentation: ${{ needs.docs-tests.result }}" >> validation-report.md
          echo "" >> validation-report.md
          echo "## Phase 3 Status" >> validation-report.md
          if [[ "${{ needs.unit-tests.result }}" == "success" && "${{ needs.state-tests.result }}" == "success" && "${{ needs.api-tests.result }}" == "success" && "${{ needs.performance-tests.result }}" == "success" && "${{ needs.security-tests.result }}" == "success" && "${{ needs.build.result }}" == "success" && "${{ needs.docs-tests.result }}" == "success" ]]; then
            echo "✅ **PHASE 3 COMPLETE** - All validation checks passed" >> validation-report.md
          else
            echo "❌ **PHASE 3 INCOMPLETE** - Some validation checks failed" >> validation-report.md
          fi

      - name: Upload validation report
        uses: actions/upload-artifact@v3
        with:
          name: phase3-validation-report
          path: validation-report.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('validation-report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
