name: Test Simple Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        type: string
        default: 'test'

jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - name: Test Step
      run: echo "Test successful"
