name: Test DriftMgr Workflow

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'basic'
        type: choice
        options:
        - basic
        - validation
        - report

jobs:
  test-driftmgr:
    name: Test DriftMgr
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build DriftMgr
      run: |
        echo "Building DriftMgr..."
        go build -o driftmgr ./cmd/main.go
        chmod +x driftmgr
        echo "✅ DriftMgr built successfully"

    - name: Test Basic Functionality
      if: github.event.inputs.test_type == 'basic'
      run: |
        echo "Testing basic DriftMgr functionality..."
        echo "DriftMgr binary exists and is executable"
        ls -la driftmgr
        echo "✅ Basic functionality test passed"

    - name: Test GitHub Actions Integration
      if: github.event.inputs.test_type == 'validation'
      run: |
        echo "Testing GitHub Actions integration..."
        ./driftmgr github-actions validate-inputs || echo "Expected failure - no environment variables"
        ./driftmgr github-actions setup-env
        echo "✅ GitHub Actions integration test passed"

    - name: Test Report Generation
      if: github.event.inputs.test_type == 'report'
      run: |
        echo "Testing report generation..."
        ./driftmgr github-actions generate-report --output test-report.md
        if [ -f "test-report.md" ]; then
          echo "✅ Report generated successfully"
          cat test-report.md
        else
          echo "❌ Report generation failed"
          exit 1
        fi

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ github.run_number }}
        path: |
          *.md
          driftmgr-data/
        retention-days: 7

    - name: Test Summary
      run: |
        echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Test Type:** ${{ github.event.inputs.test_type }}" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ✅ All tests passed" >> $GITHUB_STEP_SUMMARY
        echo "**Execution Time:** $(date)" >> $GITHUB_STEP_SUMMARY
